Alumni Profile Draft Jobs
CodeKazi/moringa-recruitment-portal pull request #13
Opened 2023-07-05 00:34 UTC by brk-a

2023-07-05 01:24 UTC, Chal13W1zz commented on components/AlumProfileBody.jsx
- The first key prop is repeated in the iterator
- The second key prop is not within the item card, this will cause your build to fail

2023-07-05 01:25 UTC, Chal13W1zz commented on components/AlumProfileHeadline.jsx
Replace the img tags with Image from next and have relevant alt props

2023-07-05 01:27 UTC, Chal13W1zz commented on src/app/alumniJobInterviewPrep.js
Have the key prop in a card

2023-07-05 01:27 UTC, Chal13W1zz requested changes
Please have a look at the requestend changes and improvements

2023-07-05 07:10 UTC, brk-a commented on components/AlumProfileBody.jsx
on it.

2023-07-05 07:29 UTC, Chal13W1zz commented on components/AlumProfileHeadline.jsx
This is yet to be resolved

2023-07-05 18:42 UTC, Chal13W1zz requested changes
Fix up this button, I think it's a missed import
![image](https://github.com/CodeKazi/moringa-recruitment-portal/assets/60155767/78ff7437-bc08-4cce-94b6-e70108321080)

2023-07-06 10:28 UTC, Chal13W1zz requested changes
Fix the broken style

2023-07-13 20:00 UTC, Chal13W1zz approved these changes
:clap: :clap:

2023-07-14 07:22 UTC, merged