added image upload modals page
CodeKazi/moringa-recruitment-portal pull request #14
Opened 2023-07-05 07:07 UTC by MaureenWanjiku

2023-07-05 07:26 UTC, pwnipc requested changes
Separate the modals into two components
- pictureUpload
and
- pictureDelete

2023-07-05 10:34 UTC, Chal13W1zz requested changes
have a look at the requested changes

2023-07-05 10:34 UTC, Chal13W1zz commented on src/app/deletephoto.js
Make this a button 
![image](https://github.com/CodeKazi/moringa-recruitment-portal/assets/60155767/17c26efa-99e2-4814-a645-2fbadbcd0002)
And add an onClick event to it that pop's up the delete confirmation dialogue box
![image](https://github.com/CodeKazi/moringa-recruitment-portal/assets/60155767/5648d731-2be8-4fd1-83d9-4fc780a39491)

2023-07-05 10:44 UTC, MaureenWanjiku commented on src/app/deletephoto.js
Okay, working on the requested changes.

2023-07-10 12:21 UTC, Chal13W1zz approved these changes

2023-07-10 12:23 UTC, merged