Added job listing page
CodeKazi/moringa-recruitment-portal pull request #6
Opened 2023-06-26 13:15 UTC by MaureenWanjiku

2023-06-26 17:15 UTC, Chal13W1zz requested changes

2023-06-26 17:15 UTC, Chal13W1zz commented on src/app/job_listing.js
Set the mock data to be fetched from a json dump, have a look at this https://github.com/CodeKazi/moringa-recruitment-portal/blob/main/cardData/recentjobs.js

2023-06-27 09:58 UTC, MaureenWanjiku commented on src/app/job_listing.js
On it

2023-06-28 10:28 UTC, Chal13W1zz approved these changes

2023-06-28 10:33 UTC, merged